### ISSUE TITLE
NV=1 fails with timeout error during init

### ISSUE THREAD

**Issue by alifuk** [tinygrad/tinygrad#6089]
**System detail:**
Ubuntu 22.04 LTS Desktop
RTX 3090 - Driver Version: 535.104.05   CUDA Version: 12.2
No other libraries / dependencies installed

**Reproduction:**
```
git clone https://github.com/tinygrad/tinygrad.git
cd tinygrad
python3 -m pip install -e .
NV=1 DEBUG=2 python3 ./examples/simple_conv_bn.py 
```

**Resulting output:**

```
opened device NPY from pid:2073301
opened device NV from pid:2073301
*** CUSTOM     1 custom_random                            mem  0.01 GB
*** CUSTOM     2 custom_random                            mem  0.01 GB 

E_392_32_4
LazyOp(MetaOps.KERNEL, arg=KernelInfo(local_dims=1, upcasted=1, dont_use_locals=False), src=(
  LazyOp(BufferOps.STORE, arg=MemBuffer(idx=0, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(392, 32, 4), strides=(128, 4, 1), offset=0, mask=None, contiguous=True),))), src=(
    LazyOp(BinaryOps.ADD, arg=None, src=(
      LazyOp(BinaryOps.MUL, arg=None, src=(
        LazyOp(BufferOps.CONST, arg=ConstBuffer(val=0.07142857142857142, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(392, 32, 4), strides=(0, 0, 0), offset=0, mask=None, contiguous=False),))), src=()),
        LazyOp(BufferOps.LOAD, arg=MemBuffer(idx=1, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(392, 32, 4), strides=(128, 4, 1), offset=0, mask=None, contiguous=True),))), src=()),)),
      LazyOp(BufferOps.CONST, arg=ConstBuffer(val=-0.03571428571428571, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(392, 32, 4), strides=(0, 0, 0), offset=0, mask=None, contiguous=False),))), src=()),)),)),))
[Opt(op=OptOps.UPCAST, axis=0, amt=4), Opt(op=OptOps.LOCAL, axis=0, amt=32)]
error lowering MetaOps.KERNEL
tensor operations:
[uniform]
Traceback (most recent call last):
  File "/home/rtx3090/Desktop/tinygrad/./examples/simple_conv_bn.py", line 14, in <module>
    for t in get_parameters([x, conv, bn]): t.realize()
  File "/home/rtx3090/Desktop/tinygrad/tinygrad/tensor.py", line 3263, in _wrapper
    ret = fn(*args, **kwargs)
  File "/home/rtx3090/Desktop/tinygrad/tinygrad/tensor.py", line 204, in realize
    run_schedule(*self.schedule_with_vars(*lst), do_update_stats=do_update_stats)
  File "/home/rtx3090/Desktop/tinygrad/tinygrad/engine/realize.py", line 221, in run_schedule
    for ei in lower_schedule(schedule):
  File "/home/rtx3090/Desktop/tinygrad/tinygrad/engine/realize.py", line 214, in lower_schedule
    raise e
  File "/home/rtx3090/Desktop/tinygrad/tinygrad/engine/realize.py", line 208, in lower_schedule
    try: yield lower_schedule_item(si)
  File "/home/rtx3090/Desktop/tinygrad/tinygrad/engine/realize.py", line 192, in lower_schedule_item
    runner = get_runner(si.outputs[0].device, si.ast)
  File "/home/rtx3090/Desktop/tinygrad/tinygrad/engine/realize.py", line 161, in get_runner
    method_cache[ckey] = method_cache[bkey] = ret = CompiledRunner(replace(prg, dname=dname))
  File "/home/rtx3090/Desktop/tinygrad/tinygrad/engine/realize.py", line 84, in __init__
    self.clprg = Device[p.dname].runtime(p.function_name, self.lib)
  File "/home/rtx3090/Desktop/tinygrad/tinygrad/runtime/ops_nv.py", line 247, in __init__
    if typ & 0xffff == 0x1204: self.device._ensure_has_local_memory(val + 0x240)
  File "/home/rtx3090/Desktop/tinygrad/tinygrad/runtime/ops_nv.py", line 530, in _ensure_has_local_memory
    self.synchronize()
  File "/home/rtx3090/Desktop/tinygrad/tinygrad/device.py", line 509, in synchronize
    self.timeline_signal.wait(self.timeline_value - 1)
  File "/home/rtx3090/Desktop/tinygrad/tinygrad/runtime/ops_nv.py", line 83, in wait
    raise RuntimeError(f"wait_result: {timeout} ms TIMEOUT!")
RuntimeError: wait_result: 10000 ms TIMEOUT!
```

**Expected output**
`CUDA=1 DEBUG=2 python3 ./examples/simple_conv_bn.py` produces:
```
opened device NPY from pid:2077952
opened device CUDA from pid:2077952
*** CUSTOM     1 custom_random                            mem  0.01 GB 
*** CUSTOM     2 custom_random                            mem  0.01 GB 
*** CUDA       3 E_392_32_4                               mem  0.01 GB tm     16.26us/     0.02ms (     6.17 GFLOPS   24.7|24.7    GB/s) ['uniform']
*** CUSTOM     4 custom_random                            mem  0.01 GB 
*** CUDA       5 E_16_4                                   mem  0.01 GB tm      7.17us/     0.02ms (     0.02 GFLOPS    0.1|0.1     GB/s) ['uniform']
running network
memory reduced from 12.45 MB -> 12.42 MB, 5 -> 4 bufs
*** CUDA       6 r_55_55_16_2_2_16_7_4_4_7                mem  0.03 GB tm   2300.93us/     2.32ms (  2150.53 GFLOPS   11.1|2117.6  GB/s) ['conv2d']
*** CUDA       7 r_220_32_4_110                           mem  0.03 GB tm     24.58us/     2.35ms (   126.04 GFLOPS  505.3|505.3   GB/s) ['mean']
*** CUDA       8 r_2_32_110                               mem  0.03 GB tm      8.96us/     2.36ms (     0.79 GFLOPS    3.2|3.2     GB/s) ['mean']
*** CUDA       9 r_2_55_32_2_4_110                        mem  0.03 GB tm     33.63us/     2.39ms (   276.52 GFLOPS  369.3|370.1   GB/s) ['__sub__', '__mul__', 'mean']
*** CUDA      10 r_2_32_110n1                             mem  0.03 GB tm     10.24us/     2.40ms (     0.71 GFLOPS    2.8|2.8     GB/s) ['mean', 'add', 'pow']
*** CUDA      11 E_4_3025_4_16_4                          mem  0.04 GB tm     41.98us/     2.44ms (   166.01 GFLOPS  590.3|737.8   GB/s) ['__sub__', 'batchnorm']
opened device CLANG from pid:2077952
*** CLANG     12 copy   12.39M,   CLANG <- CUDA           mem  0.04 GB tm   5335.07us/     7.78ms (     0.00 GFLOPS    2.3|2.3     GB/s) 
avg:   638.62 GFLOPS    11.30 GB/s           total:    12 kernels     4.97 GOPS     0.09 GB     7.78 ms

```

**Other information**
its the same for all examples. GPU, CUDA backends works as expected

**Comment by nimlgen** [comment]
Can you share your dmesg, cuz I can't reproduce this on my similar setup (rtx3090, cuda12.2)

**Comment by alifuk** [comment]
@nimlgen dmesg is here:

[mesg.txt](https://github.com/user-attachments/files/16711339/mesg.txt)

**Comment by Benetti-Hub** [comment]
Hi, I encountered the same problem this morning with a similar setup:

- **OS:** Ubuntu 22.04 LTS Desktop
- **GPU:** RTX 3060
- **CUDA Version:** 12.2

I noticed that the `nvcc` version didn’t match the CUDA version displayed by the `nvidia-smi` command (11.5 vs. 12.2). After reinstalling CUDA (now updated to 12.6) and ensuring both versions were aligned, the issue was resolved.

Here are the steps I followed:

1. **Uninstall CUDA/NVIDIA drivers:**
   ```bash
   sudo apt-get remove --purge '^nvidia-.*'
   sudo apt-get remove --purge '^libnvidia-.*'
   sudo apt-get remove --purge '^cuda-.*'
   sudo apt-get install linux-headers-$(uname -r)
   ```

2. **Install the new version of CUDA:**
   - Latest version: [NVIDIA CUDA Downloads](https://developer.nvidia.com/cuda-downloads)
   - CUDA 12.2 version: [CUDA 12.2 Archive](https://developer.nvidia.com/cuda-12-2-0-download-archive)

3. **Add `nvcc` to your `bashrc`:**
   ```bash
   export PATH=/usr/local/cuda-12.6/bin:$PATH
   export LD_LIBRARY_PATH=/usr/local/cuda-12.6/lib64:$LD_LIBRARY_PATH
   ```

4. **Install the correct drivers for your PC:**
   ```bash
   sudo ubuntu-drivers install
   ```

Hope this helps!

**Comment by alifuk** [comment]
@Benetti-Hub I did this, nvcc version and nvidia-smi version matches, but still the same issue

**Comment by keithyau** [comment]
> @Benetti-Hub I did this, nvcc version and nvidia-smi version matches, but still the same issue

did you install open source kernel driver from Nvidia ? NV=1 means running from the open source one. 

https://gist.github.com/morgangiraud/4f58a62316fac7b4a32b81f0a66893fc

**Comment by chenyuxyz** [comment]
likely stale. feel free to open a new issue if master does not work
